package simpus;

import java.awt.Color;
import javax.swing.JLabel;
import usu.widget.glass.PanelGlass;
import widget.Button;
import widget.InternalFrame;
import widget.Panel;
import widget.PanelJudul;

public class DlgAbout extends javax.swing.JDialog
{
  private Button button1;
  private InternalFrame internalFrame1;
  private JLabel jLabel1;
  private JLabel jLabel10;
  private JLabel jLabel11;
  private JLabel jLabel12;
  private JLabel jLabel13;
  private JLabel jLabel14;
  private JLabel jLabel15;
  private JLabel jLabel16;
  private JLabel jLabel18;
  private JLabel jLabel2;
  private JLabel jLabel22;
  private JLabel jLabel23;
  private JLabel jLabel24;
  private JLabel jLabel25;
  private JLabel jLabel26;
  private JLabel jLabel27;
  private JLabel jLabel28;
  private JLabel jLabel29;
  private JLabel jLabel30;
  private JLabel jLabel31;
  private JLabel jLabel32;
  private JLabel jLabel33;
  private JLabel jLabel4;
  private JLabel jLabel5;
  private JLabel jLabel6;
  private JLabel jLabel7;
  private JLabel jLabel8;
  private JLabel jLabel9;
  private javax.swing.JSeparator jSeparator1;
  private Panel panel1;
  private PanelGlass panelGlass1;
  private PanelGlass panelGlass2;
  private PanelGlass panelGlass3;
  private PanelJudul panelJudul1;
  
  public DlgAbout(java.awt.Frame paramFrame, boolean paramBoolean)
  {
    super(paramFrame, paramBoolean);
    initComponents();
    setLocation(10, 10);
    setSize(459, 490);
  }
  
  private void initComponents() {
    panelJudul1 = new PanelJudul();
    jLabel1 = new JLabel();
    jLabel2 = new JLabel();
    panel1 = new Panel();
    jLabel5 = new JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    internalFrame1 = new InternalFrame();
    jLabel6 = new JLabel();
    panelGlass1 = new PanelGlass();
    jLabel4 = new JLabel();
    jLabel7 = new JLabel();
    jLabel8 = new JLabel();
    jLabel9 = new JLabel();
    jLabel10 = new JLabel();
    jLabel11 = new JLabel();
    jLabel12 = new JLabel();
    jLabel13 = new JLabel();
    jLabel14 = new JLabel();
    jLabel15 = new JLabel();
    jLabel16 = new JLabel();
    panelGlass2 = new PanelGlass();
    jLabel22 = new JLabel();
    jLabel23 = new JLabel();
    jLabel24 = new JLabel();
    jLabel25 = new JLabel();
    jLabel26 = new JLabel();
    jLabel27 = new JLabel();
    jLabel28 = new JLabel();
    jLabel29 = new JLabel();
    jLabel30 = new JLabel();
    jLabel31 = new JLabel();
    jLabel32 = new JLabel();
    jLabel33 = new JLabel();
    panelGlass3 = new PanelGlass();
    jLabel18 = new JLabel();
    button1 = new Button();
    setDefaultCloseOperation(2);
    setModal(true);
    setResizable(false);
    setUndecorated(true);
    panelJudul1.setName("panelJudul1");
    panelJudul1.setPreferredSize(new java.awt.Dimension(440, 40));
    panelJudul1.setLayout((java.awt.LayoutManager)null);
    jLabel1.setBackground(Color.darkGray);
    jLabel1.setFont(new java.awt.Font("Book Antiqua", 3, 17));
    jLabel1.setForeground(new Color(255, 204, 255));
    jLabel1.setHorizontalAlignment(0);
    jLabel1.setText(":: ABOUT PROGRAM ::");
    jLabel1.setIconTextGap(2);
    jLabel1.setName("jLabel1");
    panelJudul1.add(jLabel1);
    jLabel1.setBounds(107, 10, 250, 21);
    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/file-edit-32x32.png")));
    jLabel2.setName("jLabel2");
    panelJudul1.add(jLabel2);
    jLabel2.setBounds(5, 0, 40, 40);
    getContentPane().add(panelJudul1, "First");
    panel1.setName("panel1");
    panel1.setPreferredSize(new java.awt.Dimension(440, 25));
    panel1.setLayout(new java.awt.BorderLayout());
    jLabel5.setBackground(Color.darkGray);
    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLabel5.setForeground(new Color(255, 204, 255));
    jLabel5.setHorizontalAlignment(0);
    jLabel5.setText(":: Terima kasih telah menggunakan produk kami ::");
    jLabel5.setName("jLabel5");
    panel1.add(jLabel5, "Center");
    jSeparator1.setBackground(new Color(0, 0, 51));
    jSeparator1.setForeground(new Color(0, 0, 51));
    jSeparator1.setName("jSeparator1");
    jSeparator1.setPreferredSize(new java.awt.Dimension(1, 1));
    panel1.add(jSeparator1, "First");
    getContentPane().add(panel1, "Last");
    internalFrame1.setName("internalFrame1");
    internalFrame1.setLayout((java.awt.LayoutManager)null);
    jLabel6.setFont(new java.awt.Font("Book Antiqua", 2, 15));
    jLabel6.setForeground(new Color(255, 255, 0));
    jLabel6.setText(".: Aplikasi ");
    jLabel6.setName("jLabel6");
    internalFrame1.add(jLabel6);
    jLabel6.setBounds(10, 8, 90, 20);
    panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(120, 15, 120)));
    panelGlass1.setOpaqueImage(false);
    panelGlass1.setRound(false);
    panelGlass1.setWarna(new Color(150, 60, 150));
    panelGlass1.setLayout((java.awt.LayoutManager)null);
    jLabel4.setForeground(new Color(205, 214, 255));
    jLabel4.setText("Server : MySQL Server");
    jLabel4.setName("jLabel4");
    panelGlass1.add(jLabel4);
    jLabel4.setBounds(72, 22, 170, 14);
    jLabel7.setForeground(new Color(205, 214, 255));
    jLabel7.setText("Nama Aplikasi : Simpus");
    jLabel7.setName("jLabel7");
    panelGlass1.add(jLabel7);
    jLabel7.setBounds(40, 8, 170, 14);
    jLabel8.setForeground(new Color(205, 214, 255));
    jLabel8.setText("Default Database : perpustakaan");
    jLabel8.setName("jLabel8");
    panelGlass1.add(jLabel8);
    jLabel8.setBounds(20, 36, 170, 14);
    jLabel9.setForeground(new Color(205, 214, 255));
    jLabel9.setText("File Konfigurasi : database.xml");
    jLabel9.setName("jLabel9");
    panelGlass1.add(jLabel9);
    jLabel9.setBounds(32, 50, 170, 14);
    jLabel10.setForeground(new Color(205, 214, 255));
    jLabel10.setText("Default Port : 3306");
    jLabel10.setName("jLabel10");
    panelGlass1.add(jLabel10);
    jLabel10.setBounds(46, 64, 170, 14);
    jLabel11.setForeground(new Color(205, 214, 255));
    jLabel11.setText("Untuk mensetting aplikasi menjadi Client");
    jLabel11.setName("jLabel11");
    panelGlass1.add(jLabel11);
    jLabel11.setBounds(230, 8, 210, 14);
    jLabel12.setForeground(new Color(205, 214, 255));
    jLabel12.setText("Server, ganti HOST Localhost dengan");
    jLabel12.setName("jLabel12");
    panelGlass1.add(jLabel12);
    jLabel12.setBounds(230, 22, 200, 14);
    jLabel13.setForeground(new Color(205, 214, 255));
    jLabel13.setText("alamat/IP Address dari server yang di");
    jLabel13.setName("jLabel13");
    panelGlass1.add(jLabel13);
    jLabel13.setBounds(230, 36, 200, 14);
    jLabel14.setForeground(new Color(205, 214, 255));
    jLabel14.setText("gunakan. Jangan lupa untuk mengatur hak");
    jLabel14.setName("jLabel14");
    panelGlass1.add(jLabel14);
    jLabel14.setBounds(230, 50, 220, 14);
    jLabel15.setForeground(new Color(205, 214, 255));
    jLabel15.setText("akses di MySQL server agar terkoneksi");
    jLabel15.setName("jLabel15");
    panelGlass1.add(jLabel15);
    jLabel15.setBounds(230, 64, 210, 14);
    internalFrame1.add(panelGlass1);
    panelGlass1.setBounds(2, 28, 454, 90);
    jLabel16.setFont(new java.awt.Font("Book Antiqua", 2, 15));
    jLabel16.setForeground(new Color(255, 255, 0));
    jLabel16.setText(".: Programer ");
    jLabel16.setName("jLabel16");
    internalFrame1.add(jLabel16);
    jLabel16.setBounds(10, 125, 110, 20);
    panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(120, 15, 120)));
    panelGlass2.setOpaqueImage(false);
    panelGlass2.setRound(false);
    panelGlass2.setWarna(new Color(150, 60, 150));
    panelGlass2.setLayout((java.awt.LayoutManager)null);
    jLabel22.setForeground(new Color(255, 255, 255));
    jLabel22.setHorizontalAlignment(0);
    jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/LaST (Cobalt) Lock n Gear.png")));
    jLabel22.setBorder(new javax.swing.border.LineBorder(new Color(255, 255, 255), 1, true));
    jLabel22.setHorizontalTextPosition(0);
    jLabel22.setName("jLabel22");
    panelGlass2.add(jLabel22);
    jLabel22.setBounds(10, 10, 178, 170);
    jLabel23.setForeground(new Color(205, 214, 255));
    jLabel23.setText("Nama : Anton Purwanto");
    jLabel23.setName("jLabel23");
    panelGlass2.add(jLabel23);
    jLabel23.setBounds(239, 12, 200, 14);
    jLabel24.setForeground(new Color(205, 214, 255));
    jLabel24.setText("");
    jLabel24.setName("jLabel24");
    panelGlass2.add(jLabel24);
    jLabel24.setBounds(201, 26, 200, 14);
    jLabel25.setForeground(new Color(205, 214, 255));
    jLabel25.setText("");
    jLabel25.setName("jLabel25");
    panelGlass2.add(jLabel25);
    jLabel25.setBounds(233, 40, 220, 14);
    jLabel26.setForeground(new Color(205, 214, 255));
    jLabel26.setText("");
    jLabel26.setName("jLabel26");
    panelGlass2.add(jLabel26);
    jLabel26.setBounds(276, 54, 160, 14);
    jLabel27.setForeground(new Color(205, 214, 255));
    jLabel27.setText("E-Mail : anton.takaful@gmail.com");
    jLabel27.setName("jLabel27");
    panelGlass2.add(jLabel27);
    jLabel27.setBounds(238, 82, 210, 14);
    jLabel28.setForeground(new Color(205, 214, 255));
    jLabel28.setText("");
    jLabel28.setName("jLabel28");
    panelGlass2.add(jLabel28);
    jLabel28.setBounds(276, 68, 140, 14);
    jLabel29.setForeground(new Color(205, 214, 255));
    jLabel29.setText("-------------------------------------------------------------");
    jLabel29.setName("jLabel29");
    panelGlass2.add(jLabel29);
    jLabel29.setBounds(200, 114, 250, 14);
    jLabel30.setForeground(new Color(205, 214, 255));
    jLabel30.setText("");
    jLabel30.setName("jLabel30");
    panelGlass2.add(jLabel30);
    jLabel30.setBounds(276, 96, 150, 14);
    jLabel31.setForeground(new Color(205, 214, 255));
    jLabel31.setText("Dilarang Keras Mengcopy/Menyebarkan aplikasi");
    jLabel31.setName("jLabel31");
    panelGlass2.add(jLabel31);
    jLabel31.setBounds(200, 130, 250, 14);
    jLabel32.setForeground(new Color(205, 214, 255));
    jLabel32.setText("ini tanpa seijin Developer.");
    jLabel32.setName("jLabel32");
    panelGlass2.add(jLabel32);
    jLabel32.setBounds(200, 144, 250, 14);
    jLabel33.setForeground(new Color(205, 214, 255));
    jLabel33.setText("Jika terjadi masalah silahkan hubungi via email");
    jLabel33.setName("jLabel33");
    panelGlass2.add(jLabel33);
    jLabel33.setBounds(200, 170, 250, 14);
    internalFrame1.add(panelGlass2);
    panelGlass2.setBounds(2, 145, 454, 200);
    panelGlass3.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(120, 15, 120)));
    panelGlass3.setOpaqueImage(false);
    panelGlass3.setRound(false);
    panelGlass3.setWarna(new Color(150, 60, 150));
    panelGlass3.setLayout((java.awt.LayoutManager)null);
    jLabel18.setFont(new java.awt.Font("Book Antiqua", 2, 18));
    jLabel18.setForeground(new Color(237, 255, 138));
    jLabel18.setText("");
    jLabel18.setName("jLabel18");
    panelGlass3.add(jLabel18);
    jLabel18.setBounds(10, 10, 330, 30);
    button1.setMnemonic('C');
    button1.setText("Close");
    button1.setToolTipText("Alt+C");
    button1.setCursor(new java.awt.Cursor(12));
    button1.setFont(new java.awt.Font("Comic Sans MS", 1, 12));
    button1.setName("button1");
    button1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent paramAnonymousActionEvent) {
        DlgAbout.this.button1ActionPerformed(paramAnonymousActionEvent);
      }
    });
    panelGlass3.add(button1);
    button1.setBounds(350, 10, 100, 30);
    internalFrame1.add(panelGlass3);
    panelGlass3.setBounds(2, 360, 454, 52);
    getContentPane().add(internalFrame1, "Center");
    pack();
  }
  
  private void button1ActionPerformed(java.awt.event.ActionEvent paramActionEvent) {
    dispose();
  }
  
  public static void main(String[] paramArrayOfString) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        DlgAbout localDlgAbout = new DlgAbout(new javax.swing.JFrame(), true);
        localDlgAbout.addWindowListener(new java.awt.event.WindowAdapter() {
          public void windowClosing(java.awt.event.WindowEvent paramAnonymous2WindowEvent) {
            System.exit(0);
          }
        });
        localDlgAbout.setVisible(true);
      }
    });
  }
}
